spring:
  profiles:
    active: local
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    driver: h2
    url: r2dbc:h2:mem:///contacts?options=DB_CLOSE_DELAY=-1
    username:
    password:
    pool:
      enabled: false
      initial-size: 5
    # console:
      # enabled: true
      # path: /r2dbc-console
  # h2:
  #  console:
  #    enabled: true
  #    path: /h2-console

# logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
server:
  port: 8888
